### ISSUE TITLE
[Question]: Solve Easy/Day 19 Task

### ISSUE THREAD

**Issue by shiwangi-07** [OPCODE-Open-Spring-Fest/code-a-licious#103]
### So, what is it about?

Examine the problem.txt file in the Easy/Day 19 folder and work out the question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushcodes000** [comment]
@shiwangi-07 please assign this task to me

**Comment by Kaizo8** [comment]
@shiwangi-07 please assign this to me

**Comment by shiwangi-07** [comment]
@ayushcodes0 this task is assigned to you, try to complete it by today. If you're unable to submit it on time,it will be assigned to @Kaizo8.
