### ISSUE TITLE
[Question]: Solve Medium/Day 10 Task

### ISSUE THREAD

**Issue by gangwarsomya** [OPCODE-Open-Spring-Fest/code-a-licious#49]
### So, what is it about?

Examine the problem.txt file in the Medium/Day 10 folder and work out the question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutosh-3474** [comment]
@shiwangi-07 kindly assign me this issue

**Comment by shiwangi-07** [comment]
@ashutosh-3474 assigned to you, try to complete it by tomorrow.

**Comment by eddy1112004** [comment]
@shiwangi-07 kindly assign me this issue
